apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-tls-cert
spec:
  secretName: default-tls-cert
  issuerRef:
    name: letsencrypt-production
  dnsNames:
  - '{{ .Values.certificateHostname }}'